# Generated by Django 3.2.13 on 2022-06-10 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=30, verbose_name='First name')),
                ('surname', models.CharField(max_length=30, verbose_name='Last name')),
                ('gender', models.CharField(choices=[('mrs', 'Mrs'), ('mr', 'Mr')], max_length=10, verbose_name='Gender')),
                ('title', models.CharField(blank=True, choices=[('Dr', 'Dr.'), ('Prof', 'Prof.')], max_length=10, null=True, verbose_name='Title')),
                ('booked', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=256, verbose_name='Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('booking_id', models.CharField(blank=True, max_length=100, verbose_name='Booking ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.patient')),
            ],
        ),
    ]
