# Generated by Django 3.2.13 on 2022-06-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='patient',
            field=models.CharField(blank=True, max_length=100, verbose_name='Booking ID'),
        ),
    ]
