# Generated by Django 3.2.13 on 2022-06-25 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20220625_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weekday',
            old_name='mentor',
            new_name='patient',
        ),
        migrations.CreateModel(
            name='AvailableHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_hour', to='booking.weekday')),
            ],
        ),
    ]
