# Generated by Django 3.2.13 on 2022-06-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20220625_1014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialist',
            new_name='Specialities',
        ),
    ]
