# Generated by Django 3.2.13 on 2022-07-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20220718_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='booked',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(null=True, verbose_name='booking date'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Booking Id'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
    ]
