# Generated by Django 3.2.13 on 2022-10-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20220721_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(null=True, verbose_name='booking time'),
        ),
    ]
