# Generated by Django 3.2.13 on 2022-10-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_booking_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='booking_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Booking Id'),
        ),
    ]
