# Generated by Django 3.2.13 on 2022-10-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20221011_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='booking_id',
            field=models.CharField(max_length=6, verbose_name='Booking Id'),
        ),
    ]
